### ISSUE TITLE
Crashes on install

### ISSUE THREAD

**Issue by rev-aggie** [ferion11/LogosLinuxInstaller#220] opened 2023-12-27 22:17 UTC
Running the CLI bash script.  (Not sure why it isn't using gui, it has before)  It crashes when it gets to "Copying: Logos_v30.1.0.0038-x64.msi\ninto: /home/keith/LogosBible10/data"  Logos install dialogue appears and then complains that Logos isn't all there.
Ubuntu 23.10

**Comment by thw26** [comment] 2023-12-27 23:45
If it has been a while since you've run the script, a recent change made it so that the script runs via CLI if initiated in a terminal emulator or by GUI if you double click it.

I haven't seen this issue before. Any other output in the CLI or an error? You can also try running the script with `-D` to get debug output; it may or may not help.

Does this happen on repeat for you?

How much disk space do you have?

**Comment by thw26** [comment] 2024-01-13 01:04
Just noticed. This tried installing Logos 30+.

Duplicate of #219

**Closed by thw26** 2024-01-13 01:04 UTC
