### ISSUE TITLE
Dot net install

### ISSUE THREAD

**Issue by arcanemuse** [ferion11/LogosLinuxInstaller#137] opened 2023-02-01 19:33 UTC
I've run the installer 3 times.  Dot net installer never runs

**Comment by arcanemuse** [comment] 2023-02-01 20:37
Update.  I ran it again this time using the appimage option.  It never ran the dot net install this time either but this time the app started and appears to be functional and at this time is downloading the 23k resources in my library.  We shall see.

**Comment by thw26** [comment] 2023-02-12 01:45
Closing as duplicate of #138.

**Closed by thw26** 2023-02-12 01:45 UTC
